apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo
  labels:
    app: kubernetes-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-demo
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
      - name: simple-node
        image: ploratran/simple-node
        ports:
        - containerPort: 80