apiVersion: v1
kind: Service
metadata:
    name: kubernetes-demo
    labels: 
        run: kubernetes-demo
spec: 
    ports: 
    - port: 80
      protocol: TCP
    selector: 
        run: kubernetes-demo